sonar.projectKey=jungle-frontend
sonar.projectName=Jungle Frontend
sonar.projectVersion=1.0.0
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/dist/**,**/coverage/**
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.typescript.tsconfigPaths=tsconfig.sonar.json
sonar.typescript.lcov.reportPaths=coverage/pi-front/lcov.info
sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=coverage/pi-front/lcov.info

