spring:
  application:
    name: ${SPRING_APPLICATION_NAME:AI-LEARNING-ASSISTANT-SERVICE}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/ai_learning_assistant_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:}

server:
  port: ${SERVER_PORT:8086}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka}
  instance:
    prefer-ip-address: ${EUREKA_INSTANCE_PREFER_IP_ADDRESS:true}
    instance-id: ${EUREKA_INSTANCE_ID:${spring.application.name}:${server.port}}
